
server.port=8081
spring.datasource.url=jdbc:sqlite:./data/mapuescuela.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
mapuescuela.uploads.dir=./data/uploads


flowable.process.rest.base-url=http://localhost:8080
flowable.process.rest.context-path=/flowable-rest/service
flowable.process.rest.definition-key=procesoDeVentaMauescuelaTOBE
flowable.process.rest.username=${FLOWABLE_REST_USERNAME:rest-admin}
flowable.process.rest.password=${FLOWABLE_REST_PASSWORD:test}

flowable.external.worker.rest.base-url=http://localhost:8080
flowable.external.worker.rest.context-path=/flowable-rest/external-job-api
flowable.external.worker.rest.authentication.basic.username=${FLOWABLE_REST_USERNAME:rest-admin}
flowable.external.worker.rest.authentication.basic.password=${FLOWABLE_REST_PASSWORD:test}
flowable.external.worker.workerId=mapuescuela-local
flowable.external.worker.polling-interval=5s
flowable.external.worker.lock-duration=5m
flowable.external.worker.number-of-retries=5
flowable.external.worker.number-of-tasks=1
flowable.external.worker.concurrency=1
